name: Deploy to Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/uninlink
          chmod 600 ~/.ssh/unilink
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/unilink
            LogLevel ERROR
            StrictHostKeyChecking no
          END

      - name: Deploy
        run: |
          ssh target "cd /var/www/unilink/repo/Unilink && \
            git fetch origin prod && \
            git checkout prod && \
            git pull origin prod && \
            docker compose down && \
            docker compose build --no-cache && \
            docker compose up -d --force-recreate"